### ISSUE TITLE
"AdapterError: Connection is already registered" w/ different adapters

### ISSUE THREAD

**Issue by xangox** [ptariche/koa-waterline#2]
Hi, thanks for the repo, it looks very promising and helpful to me.
Unfortunately, this problem happened to me with `sails-mongo` and even with `sails-mysql`, so i am expecting it isn't issue with specific adapters - the example provided here doesn't work, so I am reporting it anyways. 
Is it something w/ teardown, or is it supposed to be used in some other way than example? I have no clue.
It initializes once, but the middleware fails at another request due to IdentityDuplication or something.
With `.init()` it does the same thing. Unfortunately, I have no idea where it could be handled, so if anyone could help check it out I would be really grateful.
Thanks a lot!

**Comment by ptariche** [comment]
@xangox , I just updated koa-waterline to reflect sails-mongo and sails-mysql IdentityDuplication flag.
