### ISSUE TITLE
How to pass validation rules?

### ISSUE THREAD

**Issue by JoshZA** [ptariche/koa-waterline#5]
Heya, how do we pass validations to the schema?

[like these](https://github.com/balderdashy/anchor/blob/master/lib/match/rules.js)

I tried to define:

```
    properties: {
      name: {type: 'string', required: true, notEmpty: true},
```

but these validations get ignored

**Comment by ptariche** [comment]
Other than required, the other validation rules have not been set yet. I will add this feature. 

https://github.com/sailsjs/anchor/blob/master/lib/match/rules.js

**Comment by ptariche** [comment]
added support for attribution types of properties. You would pass like the above example. [Release Candidate](https://github.com/ptariche/koa-waterline/releases/tag/2.1.0)
