### ISSUE TITLE
Why designModel ?

### ISSUE THREAD

**Issue by troggy** [ptariche/koa-waterline#6]
@ptariche, I see that koa-waterline has it's own model definition that's then is being transformed to the waterline's one (using designModel.js). What's the deal? Why not just use [waterline's model definition format](https://github.com/balderdashy/waterline-docs/blob/master/models/models.md) directly?

Right now it's impossible to define [class and instance methods](https://github.com/balderdashy/waterline-docs/blob/master/models/instance-class-methods.md) in model, cause your model definition doesn't support these.

**Comment by troggy** [comment]
I've rewritten the module to use waterline models: https://github.com/troggy/koa-waterline/tree/v5 (not fully tested yet).
Let me know if you are interested to pull this in.

**Comment by alterx** [comment]
Besides from the fact that you can't define class and instance methods, it looks like it's impossible to use [lifecycle callbacks](https://github.com/balderdashy/waterline-docs/blob/master/models/lifecycle-callbacks.md). Maybe I'm just wrong, in that case: is there an example of how to achieve it?

Also, is there any particular reason for not using waterline's model directly?
